import org.gradle.api.publish.PublishingExtension
import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget

plugins {
    kotlin("multiplatform")
    id("com.vanniktech.maven.publish")
}

// Everything a SQLite extension package needs, so that a package is a declaration rather than a
// copy of the build logic. See SqliteExtensionSpec for what varies.
//
// The shape that matters: a package carries ONLY its own extension, compiled with -DSQLITE_CORE
// into its own static library whose sqlite3_* symbols stay unresolved. The final link satisfies
// them from the libsqlite3.a already inside kormium-sqlite's cinterop klib, which is what lets
// several extensions coexist with exactly one SQLite in the process. See Kormium ADR 0013.
val spec = extensions.create<SqliteExtensionSpec>("sqliteExtension")

// Derived lazily so a package declares only what is genuinely its own. The names must be unique
// per package: two cinterop klibs sharing a Kotlin package would collide in a project using both.
private val slug = spec.extensionName.map { it.replace('-', '_') }
spec.cinteropPackage.convention(slug.map { "c$it" })
spec.registerFunction.convention(slug.map { "kormium_register_$it" })

val kormiumVersion: String = providers.gradleProperty("kormiumVersion").get()

// The SQLite headers come from the Kormium release this will be linked into — published there as a
// `sqlite-headers` artifact — so the two cannot drift apart. A composite build does not share
// artifacts with a classifier, so a sibling checkout is read from its source tree instead.
val siblingHeaders: File = rootProject.file("../kormium/kormium-sqlite/src/nativeInterop/cinterop")
val useSiblingHeaders: Boolean =
    siblingHeaders.resolve("sqlite3.h").isFile && siblingHeaders.resolve("sqlite3ext.h").isFile

val sqliteHeaders: Configuration by configurations.creating {
    isCanBeConsumed = false
    isCanBeResolved = true
}

dependencies {
    if (!useSiblingHeaders) {
        sqliteHeaders("io.github.kormium:kormium-sqlite:$kormiumVersion:sqlite-headers@zip")
    }
}

val headersDir: Provider<Directory> = layout.buildDirectory.dir("sqlite-headers")

val unpackHeaders = tasks.register<Sync>("unpackSqliteHeaders") {
    description = "Collects sqlite3.h / sqlite3ext.h from the Kormium release being targeted"
    if (useSiblingHeaders) {
        from(siblingHeaders) { include("sqlite3.h", "sqlite3ext.h") }
    } else {
        from(provider { sqliteHeaders.map { zipTree(it) } })
    }
    into(headersDir)
}

val sourceDir: Provider<Directory> = layout.buildDirectory.dir("extension-src")

val fetchSource = tasks.register("fetchExtensionSource") {
    description = "Downloads the C this extension is built from"
    outputs.dir(sourceDir)
    doLast {
        val dir = sourceDir.get().asFile
        dir.mkdirs()
        val url = spec.sourceUrl.get()
        val downloaded = File(dir, url.substringAfterLast('/').substringBefore('?'))
        uri(url).toURL().openStream().use { input ->
            downloaded.outputStream().use { input.copyTo(it) }
        }
        if (downloaded.name.endsWith(".zip")) {
            copy {
                from(zipTree(downloaded))
                into(dir)
            }
        } else if (downloaded.name.endsWith(".tar.gz")) {
            copy {
                from(tarTree(resources.gzip(downloaded)))
                into(dir)
            }
        }
        val wanted = File(dir, spec.sourceFile.get())
        check(wanted.isFile) { "${spec.sourceFile.get()} not found in $url" }
    }
}

// The C shim is generated rather than written per package: it is the same three lines every time,
// and the only things that vary — the entry point and the symbol names — are already declared.
val generatedDef: Provider<RegularFile> = layout.buildDirectory.file("cinterop/extension.def")

val generateDef = tasks.register("generateCinteropDef") {
    description = "Generates the cinterop def that registers this extension's entry point"
    outputs.file(generatedDef)
    doLast {
        val file = generatedDef.get().asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            package = ${spec.cinteropPackage.get()}

            # Generated by the kormium-sqlite-extension convention plugin.
            #
            # sqlite3_auto_extension applies the entry point to every connection opened afterwards,
            # which is how a whole pool gets the extension from one call. The archive linked here
            # holds only this extension; its sqlite3_* references are satisfied at the final link.
            ---
            #include "sqlite3.h"

            int ${spec.entryPoint.get()}(sqlite3*, char**, const void*);

            static int ${spec.registerFunction.get()}(void) {
                return sqlite3_auto_extension((void(*)(void)) ${spec.entryPoint.get()});
            }
            """.trimIndent() + "\n",
        )
    }
}

kotlin {
    explicitApi()
    jvmToolchain(21)

    val konanDataDir = System.getenv("KONAN_DATA_DIR")?.let(::File)
        ?: File(System.getProperty("user.home"), ".konan")
    val konanVersion = "2.4.10"
    fun runKonan(): List<String> {
        val dist = (konanDataDir.listFiles { f ->
            f.isDirectory && f.name.startsWith("kotlin-native-prebuilt-") && f.name.endsWith(konanVersion)
        } ?: emptyArray<File>()).firstOrNull()
            ?: error("Kotlin/Native $konanVersion toolchain not found under $konanDataDir")
        return if (System.getProperty("os.name").startsWith("Windows"))
            listOf("cmd", "/c", dist.resolve("bin/run_konan.bat").absolutePath)
        else
            listOf(dist.resolve("bin/run_konan").absolutePath)
    }

    listOf(
        linuxX64(), macosX64(), macosArm64(), mingwX64(),
        iosX64(), iosArm64(), iosSimulatorArm64(),
    ).forEach { target ->
        val konanName = target.konanTarget.name
        val capName = target.targetName.replaceFirstChar { it.uppercase() }
        val outDir = layout.buildDirectory.dir("extension/$konanName")
        val objFile = outDir.map { it.file("extension.o") }
        val staticLib = outDir.map { it.file("libextension.a") }

        val compile = tasks.register<Exec>("compileExtension$capName") {
            // The Kotlin/Native toolchain compiles this C, and on a clean machine it is not there
            // until Gradle fetches it — nothing else in this graph would ask, since cinterop (the
            // first thing that needs it) runs later.
            dependsOn(fetchSource, unpackHeaders, "downloadKotlinNativeDistribution")
            inputs.dir(sourceDir)
            inputs.dir(headersDir)
            outputs.file(objFile)
            doFirst {
                objFile.get().asFile.parentFile.mkdirs()
                // Through a response file: run_konan swallows `-DFOO=1` passed directly (its JVM
                // launcher takes them for system properties), which would silently drop
                // -DSQLITE_CORE and build a loadable extension instead of a static one. This
                // happens on every host, not only Windows.
                fun q(f: File) = "\"" + f.absolutePath.replace('\\', '/') + "\""
                val source = File(sourceDir.get().asFile, spec.sourceFile.get())
                val rsp = objFile.get().asFile.resolveSibling("clang-args.rsp")
                rsp.writeText(
                    (
                        listOf("-O2", "-DSQLITE_CORE=1") + spec.extraDefines.get() +
                            listOf(
                                "-I" + headersDir.get().asFile.absolutePath,
                                "-I" + sourceDir.get().asFile.absolutePath,
                                "-c", q(source), "-o", q(objFile.get().asFile),
                            )
                        ).joinToString("\n"),
                )
                commandLine(runKonan() + listOf("clang", "clang", konanName, "@" + rsp.absolutePath))
            }
        }
        val archive = tasks.register<Exec>("archiveExtension$capName") {
            dependsOn(compile)
            inputs.file(objFile)
            outputs.file(staticLib)
            doFirst {
                commandLine(
                    runKonan() + listOf(
                        "llvm", "llvm-ar", "rcs",
                        staticLib.get().asFile.absolutePath, objFile.get().asFile.absolutePath,
                    ),
                )
            }
        }

        target.compilations.getByName("main").cinterops {
            register("extension") {
                defFile(generatedDef.get().asFile)
                compilerOpts("-I${headersDir.get().asFile.absolutePath}")
                extraOpts("-staticLibrary", "libextension.a", "-libraryPath", outDir.get().asFile.absolutePath)
            }
        }
        tasks.named("cinteropExtension$capName").configure {
            dependsOn(archive, unpackHeaders, generateDef)
            // The header, the def and the archive reach cinterop through compilerOpts/extraOpts,
            // which Gradle cannot see; without declaring them the klib stays up to date across a
            // version bump and the old extension silently stays linked in.
            inputs.dir(headersDir)
            inputs.file(generatedDef)
            inputs.file(staticLib)
        }
    }

    // No wasmJs here on purpose: whether a package can serve Node depends on whether its
    // extension publishes a prebuilt binary for it, which only the package knows. Those that can
    // add `wasmJs { nodejs() }` themselves.

    applyDefaultHierarchyTemplate()

    sourceSets {
        val commonMain by getting {
            dependencies {
                api("io.github.kormium:kormium-sqlite-spi:$kormiumVersion")
            }
        }
        val nativeTest by getting {
            dependencies {
                implementation(kotlin("test"))
                implementation("io.github.kormium:kormium-sqlite:$kormiumVersion")
            }
        }
    }
}
